### ISSUE TITLE
Inquiring about the oscillation issue in UMI control trajectory

### ISSUE THREAD

**Issue by JinmingM** [Fanqi-Lin/Data-Scaling-Laws#1]
Hi,

After employing the Diffusion Policy to generate a sequence of 16 actions, when steps_per_inference is set to 6, the robotic arm exhibits a oscillation phenomenon after executing 6 actions and transitioning to the next sequence of actions derived from the subsequent inference.

Upon visualizing the execution trajectory of the robotic arm, I observed that the oscillation issue occurs each time there is a transition from the trajectory inferred in the previous cycle to the new trajectory inferred in the current cycle (the two trajectories do not coincide). It is hypothesized that the inconsistency of the Diffusion Policy may be the underlying cause of this issue.

Your experimental video shows the robotic arm's trajectory to be very smooth. How did you achieve this?

**Comment by Fanqi-Lin** [comment]
We also observe the oscillation phenomenon between the transitions. To address this, we employed a temporal ensemble approach, which is detailed in the policy learning section of our paper.

For a more specific implementation, you can refer to our code [here](https://github.com/Fanqi-Lin/Data-Scaling-Laws?tab=readme-ov-file#-real-world-evaluation). The temporal_agg parameter can be adjusted to incorporate the temporal ensemble method.
