### ISSUE TITLE
what is your moving lift table?

### ISSUE THREAD

**Issue by Bailey-24** [Fanqi-Lin/Data-Scaling-Laws#2]
Could you please give a taobao link to this table?
and how do you install the franka into the table?
![image](https://github.com/user-attachments/assets/03b7b001-c8a7-4f04-9b76-8fcb68aa17b7)

**Comment by Yingdong-Hu** [comment]
Table: http://e.tb.cn/h.TbxXTZFHRqcxIJZ?tk=t3xJ3I8oCrH (buy a lifting table frame and two desk panels, panel size: 660 * 586)
Wheel: http://e.tb.cn/h.TbQ2ESbINzsh9XX?tk=5EfQ3I8MCGA (4 inch AB type brake)

We drilled holes in the appropriate locations on the table and install Franka.
